# Generated by Django 2.0.4 on 2018-07-23 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Assassinate', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Assassinate', max_length=20)),
                ('tran_date', models.DateTimeField(auto_now_add=True)),
                ('player1', models.CharField(default='Lee', max_length=20)),
                ('player2', models.CharField(default='Lee', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(default='Assassin', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CardInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuffle_order', models.IntegerField(null=True)),
                ('status', models.CharField(blank=True, choices=[('U', 'Up'), ('D', 'Down')], default='D',
                                            help_text='Card status', max_length=1)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coup.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(to='coup.CardInstance')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUM_OF_CARDS', models.IntegerField(default=2)),
                ('whoseTurn', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(default='Lee', max_length=20)),
                ('playerNumber', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=2)),
                ('hand', models.ManyToManyField(to='coup.CardInstance')),
            ],
        ),
    ]
