# Generated by Django 2.0.4 on 2018-07-23 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('coup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionHistory',
        ),
    ]
