# Generated by Django 2.0.4 on 2018-07-23 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('coup', '0003_actionhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionHistory',
        ),
    ]
