# Generated by Django 2.0.4 on 2018-07-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coup', '0007_auto_20180726_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_action',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
