# Generated by Django 2.0.4 on 2018-07-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coup', '0012_function_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discardRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='redo',
            field=models.BooleanField(default=True),
        ),
    ]
