# Generated by Django 2.0.4 on 2018-08-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coup', '0015_action_coins_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='discardRequired',
        ),
        migrations.AddField(
            model_name='game',
            name='pending_action',
            field=models.BooleanField(default=False),
        ),
    ]
