# Generated by Django 2.0.4 on 2018-08-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coup', '0020_game_redomessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='redo',
            field=models.BooleanField(default=False),
        ),
    ]
