# Generated by Django 2.0.4 on 2018-08-10 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('coup', '0021_auto_20180810_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='redo',
        ),
    ]
