# Generated by Django 2.0.4 on 2018-08-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coup', '0031_auto_20180824_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='coins_to_lose_in_challenge',
            field=models.IntegerField(default=0),
        ),
    ]
