# Generated by Django 2.0.4 on 2018-09-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coup', '0033_action_card_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionhistory',
            name='challenge_loser',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='actionhistory',
            name='challenge_winner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
