# Generated by Django 2.0.4 on 2018-07-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coup", "0014_game_redomessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="coins_required",
            field=models.IntegerField(default=0),
        ),
    ]
