# Generated by Django 2.0.4 on 2018-08-08 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coup", "0016_auto_20180808_1111"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="redoMessage",
        ),
    ]
