# Generated by Django 2.0.4 on 2018-07-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0003_auto_20180615_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='died'),
        ),
    ]
